Repository hyprutils/hyprparser, pull requests merged in 2024-11, with the labels that each got.

#16 bump ver
  README.md
Labels: documentation

#17 add support for $HOME and variables with paths
  src/lib.rs
Labels: enhancement

#18 v0.1.3
  Cargo.lock
  Cargo.toml
Labels: enhancement

#19 fix: parser taking comments as parts of paths
  Cargo.lock
  Cargo.toml
  src/lib.rs
Labels: bug

#20 implement dynamic indentation
  src/lib.rs
Labels: enhancement

#21 docs: update the wording
  README.md
Labels: documentation

#22 fix dumping
  src/lib.rs
Labels: bug

#27 docs: fix rustdoc tests
  .github/workflows/rust.yml
  src/lib.rs
Labels: documentation

#28 docs: add the Grind badge
  README.md
Labels: documentation
